# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.12'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: K0RVRL1yfQHbFRvwEae5Qp6qCdLvxZdMTh8T7sQG6Bhp5s5rtWTIVt0ZYNQoZxec1XT+iftSeS6Dgh5X4/DUZGdNR+/f6uw2IrZnMfGaZXFJ03eAxAdFwpNUmw9zB4KGMvHqWGPsqIQpCVbInRPFmYIO+cBDI88oQT46o2jXgSKLTRZmoHYQ+iAMwwb+BUrDVGaA1DtIscqT9LWgyrSn2BgyjvaTW1hr2l83len0x9q6cR3e1lz+uEsPQo1NRPRo1VZynwmeIRAQaAx71WQZfXjRDBo7LsKjobYKclYKiGQkTMPFIWgrrQsQxkJYhSpyDpmYoux2O/D/Ygzs2I/ppMNH5TR7MsXMa3OvCQSLqUAdas4JWRU5cKguyaL/d01pp4UNSjwQzLaKVWxFyZoeCHyFQ8Q8CTs9zBhcphMbxAcTjcJH9l4BnMh5lJeYUrqOnamdyASw6rV8yus2uC625FCbUd91Sxqm2B2yH9rWR0joQUNB5DIlawkP624jVwLSeBQa6dQ5akXN9ofbNx5XpcEtPdV5alCoiJ7fbJZsc6PSTrWGcIolmh2D1Y5s466+F4DTQD3/Jfvt1yTsbLjzWnjRZ+8Xf69TNcHm/rnyA3DXHvu+VCSjCg2L0PZou6XGPwwGk68iWiu6NAHajEyPb2omVNA8kws8hfKyI4v1Psg=
    # SAUCE_TOKENS
    - secure: vNj/uju0IkFDw9AdhK0ggugK68VZfe5Dw3aGb9Zpk2tGD2efX1CkUopChor1GYyisTPDUEi66ko82lrrJeDGxj6VM2qwVdrZqFiSfaOImUbiVKZdp3DckZWz+RCaqBJtOCiCEwyNOhhviLmNTwLXBusgGstcVHZVVv9aC9K34brBouRgp5QNq70XRHAX+Izyon5IwGg4qPrEITrDQ3QmCVw/tlCaCvR4garrJh+1bjQfLM/w8/efe0a8sgm9B/KaXXUvGQd+Z3DbF2MkOze7Bwdw6k60xX1hGlutf3ZZakeR5T0vFUzxZpmPmuW35efP281gwP47RWSiDBl19g3JC4TKf9lIcTRH5xLGyKZ8+jdat5zPn/u5AnGERTA/TMPlOSIxNk4fYItkWmFOvoyo17U9hQbmXrkm8zFVVDVoH92UNP5RLcsxyvz4nJ+ehSnWD5XkdIeN1emcJj/gtlnu8yijyspC+gC9A9hBSvOBi7WTTIG5oNYxZTuEDe77idNn3DxxhMHXNgD844AG1SR9foPAQrWC28hh/TnhunKlTVqporUzXUynJjSysKcITxDGLcfQAeME6kSjX1eZGIz34qC21tCYCUedqkoInj7DMw/ZgqoQPVwBmK+Y2z0TMd1R7RdkxiLdfiOoDeRVNjO8nMo5cQP3SORndQ3pS+G6xzI=
    - secure: FFGu/+koGZoJEzJuHhInsoPn/ljF6mYmEc+jaOhmV14tmi82JP/R2BnhuIz2iXZALOGbbOL05Dfq94s4DTWMSGAJPSbrwHS8qmXREnpKYdX7z1uC4cJGNdxGmHkTzvEblrmoPrsxdd7f8klFMooedDHFD3YjyvPbeKQx6K14QyHUDTIeOOmH7ZWioRMQP/YpF83DApawVNRBodGo2RZZ9k0Qp+ngXgjyJvvfzkZjOnWYof4QvR2Ww2ShDOu0bWprEXDDH3IUlOv8SZyzevohM2JQ+sqrFrfp7hqD5hXMW2VQBqZ0t/mRb638tsjEyUO5QG6fNpMnpVDZII7yNVrQhCLRZ7uWsae2+xKdjkVHx+vwhUQ4fbWs8Z8jBNqNEGMvAbNGZsgC7s3SQfYxvBc02cdC6xukPY9JSvOvNB9lr3niuIFScVNEXiTOZU8wGm2JKb1fr/CXVXaplFTkR9by9jD/s64dhARTv4JcFc0FJfRGAXKXfhhCkBrtL83QWKZXimq8lTqwqhsR6kM8XcwQbIT1rywsgW13C13ptqsGMT/f08xhhlY9zWXYVv6bSuz1F+Hwg3E8T/zTCd9kpqeDzRA1oFMG1RlgHxuF47CsSuCjfJkD974WYHEgL+qnHTCILqwhy4mzAG3PXia7kZELv3FnDbh8FqgD35MkEGO2u+Y=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: P8LcEoufnosf0SbU3oieUzvkaggKSS5AcnV3xF1MyH/VDpkovtzRKyc8bCYXr+JIq3V/+/g9FP4tj/NLNRdmXXootR+4CykxanWRg3HOF0rcdARtBjPXu62Dz0irWhJyx8LMf13Cs3lswDMb0WkHIKzVQMUe08Ph+VdAAAgKwVGmgHZ5xZ8BRPNBCKMqncwvDSJuysTpy1sucpuYPdWwxPkDryDqVE2BF/G+qhgNMr99eh3JmlEAF+7Bthl0s4SfBJR+BLJVVQdJqPQvTJ2uXjbMRSRddcO/VLaDHG1o3PWEShCHFoNwjdzXEnsAI7cOziPYh4UQv16hwbmnk2w0H3OY3U5P3x/ZpfDTR9fl8kTA0+vNnIGTFJy+FTw3Z915mz3fQRphGQe3cd6GyMxn1x86pRD24EQxlchTiP2IwcSG0n5s/eCSgp9yMrdfz8IlF0o33GqAbnfP/Tk/CnrljEvge0w3sWgJnwZqb+EW1SXhQK46G/9Tc15bvLhfzqK9nl4DRn8aBvC5qyHIGLEUITUrAWZL6ceICjUVVc+PyuUEyt0swyrePTQdWoB85YTURK5U1pKgFwbk1o+9QzXEU4fUVB0p/NEx5sRmJMKcdHDYa36g9KHc6mDFEnaKwd3NIShsTwC4wXBNQc9JFKMsBNP9VNurpZvUellJwFhcqh4=

# Cloud testing
after_deploy:
  - npm install
  - npm run test-cloud
